接入了萌娘百科, 已完成搜索功能
LiteyukiStudio/nonebot-plugin-marshoai pull request #22
Opened 2024-12-10 16:16 UTC by Twisuki

# 喵~
## 喵~
### 喵~
#### 喵~
##### 喵~
###### 喵~

**喵~** ~喵\~~ _喵~_

> 喵~

[喵~](喵~)

2024-12-10 16:24 UTC, Asankilp requested changes
喵

2024-12-10 16:24 UTC, Asankilp commented on nonebot_plugin_marshoai/tools/marshoai-meogirl/mg_Search.py
> +def search(msg : str, num : int):
须使用async def定义函数，并且使用httpx的异步请求方法，不可以使用requests

2024-12-10 16:25 UTC, Asankilp commented on nonebot_plugin_marshoai/tools/marshoai-meogirl/mg_Search.py
> +def search(msg : str, num : int):
需要在`pyproject.toml`添加BeautifulSoup依赖项

2024-12-10 17:03 UTC, ChlorideP commented
so 怎么个事（

2024-12-10 17:54 UTC, Twisuki commented
咱本地push上去，pr未关闭情况下会自动pr进来？

2024-12-10 19:19 UTC, ChlorideP commented
> 咱本地push上去，pr未关闭情况下会自动pr进来？

不知道喵

2024-12-10 19:20 UTC, ChlorideP commented
经过调试，姑且是能用。不过这嵌套个人觉得还有改进空间（

2024-12-11 01:31 UTC, EillesWan commented
我来看看~

2024-12-11 01:39 UTC, EillesWan commented
你把它 Merge 到 Dev 分支下面，我来修复问题

2024-12-11 10:43 UTC, Asankilp approved these changes

2024-12-11 10:43 UTC, merged

2024-12-11 10:43 UTC, Twisuki commented
修复完成，目前已经能用了，~但仅限于能用~

后续考虑优化下代码，目前写得很烂

2024-12-11 12:30 UTC, ChlorideP commented
> 后续考虑优化下代码，目前写得很烂

我再读读看（）昨天那版至少可以反转下 if。